version: "2"
run:
  tests: true
linters:
  enable:
    - cyclop
    - funlen
    - gocognit
    - gocyclo
  disable:
    - errcheck
    - staticcheck
    - unused
  settings:
    cyclop:
      max-complexity: 8
    funlen:
      lines: 20
      statements: 15
      ignore-comments: false
    gocyclo:
      min-complexity: 8
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - cyclop
          - funlen
          - gocognit
          - gocyclo
        path: _test\.go
      - linters:
          - cyclop
          - funlen
          - gocognit
          - gocyclo
        path: cmd/mau/mau\.go
      - linters:
          - cyclop
        path: (.+)_test\.go
    paths:
      - vendor
      - .git
      - .github
      - gotk4-adwaita
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
