linters:
  disable:
    - errcheck      # Pre-existing unchecked errors throughout codebase
    - unused        # Pre-existing unused fields (account.go:339)
    - gosimple      # Pre-existing simplification opportunities
    - ineffassign   # Pre-existing ineffectual assignments in tests
    - staticcheck   # Pre-existing deprecated openpgp usage
  disable-all: false
  
  enable:
    - gofmt
    - goimports

linters-settings:
  govet:
    disable:
      - fieldalignment  # Pre-existing struct alignment issues
      - shadow          # Pre-existing variable shadowing
      - lostcancel      # Pre-existing context leak issues
  
run:
  timeout: 5m
  go: '1.26'

issues:
  exclude-use-default: false
