/**
 * Network configuration for the Mau GUI
 * 
 * Bootstrap peers are used for initial DHT network join.
 * During development, a local Go server acts as the bootstrap peer.
 */

import type { Peer } from '@mau-network/mau';
import type { ConnectionManagerConfig } from '../network/connection-manager';

/**
 * Development bootstrap peer configuration
 * 
 * This fingerprint is generated by the dev-server.sh script.
 * Run `bun run dev:peer` to start the bootstrap peer and see the fingerprint.
 * 
 * IMPORTANT: The fingerprint below is a placeholder. Update it with the actual
 * fingerprint from your dev server, or set VITE_DEV_PEER_FINGERPRINT in .env
 */
const DEV_BOOTSTRAP_FINGERPRINT = import.meta.env.VITE_DEV_PEER_FINGERPRINT || '';
const DEV_BOOTSTRAP_ADDRESS = import.meta.env.VITE_DEV_PEER_ADDRESS || 'localhost:8081';

/**
 * Production bootstrap peers
 * 
 * These are public bootstrap peers that help GUI clients join the DHT network.
 * Add production bootstrap peers here when available.
 */
const PRODUCTION_BOOTSTRAP_PEERS: Peer[] = [
  // Example: { fingerprint: 'abc123...', address: 'bootstrap.mau.network:443' }
];

/**
 * Get network configuration based on environment
 */
export function getNetworkConfig(): ConnectionManagerConfig {
  const isDevelopment = import.meta.env.DEV;
  
  const bootstrapPeers: Peer[] = [];
  
  if (isDevelopment && DEV_BOOTSTRAP_FINGERPRINT) {
    console.log('[NetworkConfig] Using development bootstrap peer');
    bootstrapPeers.push({
      fingerprint: DEV_BOOTSTRAP_FINGERPRINT,
      address: DEV_BOOTSTRAP_ADDRESS,
    });
  } else if (!isDevelopment) {
    console.log('[NetworkConfig] Using production bootstrap peers');
    bootstrapPeers.push(...PRODUCTION_BOOTSTRAP_PEERS);
  } else {
    console.warn('[NetworkConfig] No bootstrap peers configured');
    console.warn('[NetworkConfig] Set VITE_DEV_PEER_FINGERPRINT in .env or run dev-server.sh');
  }
  
  return {
    bootstrapPeers,
    iceServers: [
      { urls: 'stun:stun.l.google.com:19302' },
    ],
  };
}
